# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Team.create(name:'Designated Drinkers', point_of_contact_id: '1')
Team.create(name:'The Mighty Morphin Flower Arrangers', point_of_contact_id: '2')
Team.create(name:'e-LEMON-ators', point_of_contact_id: '3')
Team.create(name:'Master Minds', point_of_contact_id: '4')
Team.create(name:'One Hit Wonders', point_of_contact_id: '5')
Team.create(name:'Hit for Brains', point_of_contact_id: '6')
Team.create(name:'The Mullet Mafia', point_of_contact_id: '7')
Team.create(name:'Man-Eating Squirrels', point_of_contact_id: '8')
Team.create(name:'Bad Intentions', point_of_contact_id: '9')
Team.create(name:'The Wet Wedgies', point_of_contact_id: '10')
Team.create(name:'Super Heroes In Training', point_of_contact_id: '11')
Student.create(first_name: 'Mariel', last_name: 'Silver', team_id: '1', email: 'test0@gmail.com', interests: 'reading')
Student.create(first_name: 'Jasmine', last_name: 'Deborde', team_id: '2', email: 'test1@gmail.com', interests: 'eating')
Student.create(first_name: 'Latarsha', last_name: 'Vandermolen', team_id: '3', email: 'test2@gmail.com', interests: 'reading')
Student.create(first_name: 'Garnett', last_name: 'Smullen', team_id: '4', email: 'test3@gmail.com', interests: 'swimming')
Student.create(first_name: 'Jordon', last_name: 'Mutch', team_id: '5', email: 'test4@gmail.com', interests: 'running')
Student.create(first_name: 'Antonio', last_name: 'Krawczyk', team_id: '6', email: 'test5@gmail.com', interests: 'software engineering')
Student.create(first_name: 'Winfred', last_name: 'Hutchings', team_id: '7', email: 'test6@gmail.com', interests: 'software engineering')
Student.create(first_name: 'Pia', last_name: 'Teachout', team_id: '8', email: 'test7@gmail.com', interests: 'skateboarding')
Student.create(first_name: 'Ellen', last_name: 'Brar', team_id: '9', email: 'test8@gmail.com', interests: 'software engineering')
Student.create(first_name: 'Danita', last_name: 'Alleman', team_id: '10', email: 'test9@gmail.com', interests: 'running')
Student.create(first_name: 'Renee', last_name: 'Righter', team_id: '11', email: 'test0@gmail.com', interests: 'soccer')
Student.create(first_name: 'Marjorie', last_name: 'Ladner', team_id: '10', email: 'test1@gmail.com', interests: 'basketball')
Student.create(first_name: 'Deandre', last_name: 'Holland', team_id: '0', email: 'test2@gmail.com', interests: 'soccer')
Student.create(first_name: 'Lilly', last_name: 'Kral', team_id: '8', email: 'test3@gmail.com', interests: 'sleeping')
Student.create(first_name: 'Rosamaria', last_name: 'Thrailkill', team_id: '0', email: 'test4@gmail.com', interests: 'swimming')
Student.create(first_name: 'Irish', last_name: 'Carreras', team_id: '6', email: 'test5@gmail.com', interests: 'swimming')
Student.create(first_name: 'Mireille', last_name: 'Gaudette', team_id: '2', email: 'test6@gmail.com', interests: 'eating')
Student.create(first_name: 'Larissa', last_name: 'Denson', team_id: '6', email: 'test7@gmail.com', interests: 'basketball')
Student.create(first_name: 'Willetta', last_name: 'Pfeifer', team_id: '8', email: 'test8@gmail.com', interests: 'software engineering')
Student.create(first_name: 'Mickey', last_name: 'Sea', team_id: '3', email: 'test9@gmail.com', interests: 'software engineering')
Student.create(first_name: 'Emelia', last_name: 'Biondo', team_id: '3', email: 'test10@gmail.com', interests: 'software engineering')
Student.create(first_name: 'Emery', last_name: 'Hamaker', team_id: '10', email: 'test11@gmail.com', interests: 'basketball')
Student.create(first_name: 'Ursula', last_name: 'Abrahamson', team_id: '3', email: 'test12@gmail.com', interests: 'eating')
Student.create(first_name: 'Rosalina', last_name: 'Admire', team_id: '1', email: 'test13@gmail.com', interests: 'programming')
Student.create(first_name: 'Sasha', last_name: 'Dorfman', team_id: '1', email: 'test14@gmail.com', interests: 'reading')
Student.create(first_name: 'Dagmar', last_name: 'Napier', team_id: '3', email: 'test15@gmail.com', interests: 'sleeping')
Student.create(first_name: 'Kevin', last_name: 'Toller', team_id: '1', email: 'test16@gmail.com', interests: 'swimming')
Student.create(first_name: 'Danille', last_name: 'Lurry', team_id: '5', email: 'test17@gmail.com', interests: 'reading')
Student.create(first_name: 'Kaycee', last_name: 'Collar', team_id: '3', email: 'test18@gmail.com', interests: 'sleeping')
Student.create(first_name: 'Clifton', last_name: 'Dalrymple', team_id: '5', email: 'test19@gmail.com', interests: 'eating')
Student.create(first_name: 'Bruno', last_name: 'Funkhouser', team_id: '6', email: 'test20@gmail.com', interests: 'golfing')
Student.create(first_name: 'Jerrell', last_name: 'Zeman', team_id: '1', email: 'test21@gmail.com', interests: 'soccer')
Student.create(first_name: 'Lore', last_name: 'Mcquay', team_id: '1', email: 'test22@gmail.com', interests: 'programming')
Student.create(first_name: 'Jani', last_name: 'Mcglothlen', team_id: '3', email: 'test23@gmail.com', interests: 'basketball')
Student.create(first_name: 'Fredia', last_name: 'Joshua', team_id: '8', email: 'test24@gmail.com', interests: 'eating')
Student.create(first_name: 'Alysia', last_name: 'Withey', team_id: '7', email: 'test25@gmail.com', interests: 'swimming')
Student.create(first_name: 'Samira', last_name: 'Mccandless', team_id: '8', email: 'test26@gmail.com', interests: 'swimming')
Student.create(first_name: 'Candyce', last_name: 'Beecham', team_id: '0', email: 'test27@gmail.com', interests: 'golfing')
Student.create(first_name: 'Kim', last_name: 'Canto', team_id: '8', email: 'test28@gmail.com', interests: 'software engineering')
Student.create(first_name: 'Marlena', last_name: 'Bachicha', team_id: '10', email: 'test29@gmail.com', interests: 'programming')
Student.create(first_name: 'Henry', last_name: 'Meinke', team_id: '10', email: 'test30@gmail.com', interests: 'running')
Student.create(first_name: 'Maire', last_name: 'Nott', team_id: '8', email: 'test31@gmail.com', interests: 'basketball')
Student.create(first_name: 'Matilde', last_name: 'Sparks', team_id: '6', email: 'test32@gmail.com', interests: 'swimming')
Student.create(first_name: 'Madison', last_name: 'Nay', team_id: '6', email: 'test33@gmail.com', interests: 'sleeping')
Student.create(first_name: 'Jacques', last_name: 'Perrone', team_id: '9', email: 'test34@gmail.com', interests: 'reading')
Student.create(first_name: 'Melvin', last_name: 'Chen', team_id: '0', email: 'test35@gmail.com', interests: 'sleeping')
Student.create(first_name: 'Delorse', last_name: 'Hart', team_id: '9', email: 'test36@gmail.com', interests: 'sleeping')
Student.create(first_name: 'Tyler', last_name: 'Speas', team_id: '3', email: 'test37@gmail.com', interests: 'sleeping')
Student.create(first_name: 'Normand', last_name: 'Hires', team_id: '9', email: 'test38@gmail.com', interests: 'eating')
Student.create(first_name: 'Julienne', last_name: 'Fleener', team_id: '0', email: 'test39@gmail.com', interests: 'software engineering')
Student.create(first_name: 'Theo', last_name: 'Roysden', team_id: '10', email: 'test40@gmail.com', interests: 'software engineering')
Student.create(first_name: 'Frederick', last_name: 'Linder', team_id: '8', email: 'test41@gmail.com', interests: 'soccer')
Student.create(first_name: 'Glenna', last_name: 'Cogdill', team_id: '1', email: 'test42@gmail.com', interests: 'programming')
Student.create(first_name: 'Earnestine', last_name: 'Sheppard', team_id: '4', email: 'test43@gmail.com', interests: 'eating')
Student.create(first_name: 'Nakesha', last_name: 'Trout', team_id: '5', email: 'test44@gmail.com', interests: 'golfing')
Student.create(first_name: 'Kizzie', last_name: 'Lauritzen', team_id: '2', email: 'test45@gmail.com', interests: 'reading')
Student.create(first_name: 'Tamica', last_name: 'Mckie', team_id: '3', email: 'test46@gmail.com', interests: 'running')
Student.create(first_name: 'Genny', last_name: 'Ingwersen', team_id: '7', email: 'test47@gmail.com', interests: 'software engineering')
Student.create(first_name: 'Mavis', last_name: 'Strohmeyer', team_id: '8', email: 'test48@gmail.com', interests: 'sleeping')
Student.create(first_name: 'Terisa', last_name: 'Cavender', team_id: '4', email: 'test49@gmail.com', interests: 'golfing')